import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
//import App from './App';
//import Apptable from './Apptable';
import AppApi from './AppApi';
import RouteBasic from './RouteBasic';
import registerServiceWorker from './registerServiceWorker';
import ModalSwitch from './ModalGallery';
ReactDOM.render(<RouteBasic />, document.getElementById('root'));
registerServiceWorker();
